export const globalFormInput = {
  assetType: "Select Asset Type",
  country: "",
  city: "",
  phoneNumber: "",
  neighbourhood: "",
  propertyType: "",
  title: "",
  slug: "",
  pictures: null,
  video: null,
  thumbnailImg: null,
  qrScan: null,
  agencyAgreement: null,
  evaluationCertificate: null,
  video3DWalkthrough: "",
  technicalReport: "",
  evaluationDateTime: "",
  price: "",
  priceFrom: "",
  priceTo: "",
  description: "",
  additionalDescription: "",
  bedrooms: "",
  bathrooms: "",
  developer: "",
  advertisementId: "",
  dldNumber: "",
  sizeSQFT: "",
  sizeSQM: "",
  sizeSQFTFrom: "",
  sizeSQFTTo: "",
  sizeSQMFrom: "",
  sizeSQMTo: "",
  sizeType: "SQFT",
  qrScan: null,
  deliveryQuarter: "",
  deliveryYear: "",
  layout: "",
  numberOfFloors: "",
  availableApartment: "",
  paymentPlan: [],
  facilities: [],
  listings: [],
};

export const globalFormInputFields = [
  {
    type: "text",
    label: "Title your property",
    placeholder: "Title your property (max. 30 characters)",
    name: "title",
    maxLength: 30,
    required: true,
  },
  {
    type: "phoneNumber",
    label: "Phone Number",
    name: "phoneNumber",
    placeholder: "Enter your phone number",
    required: true,
  },
  {
    type: "file",
    mediaType: "thumbnail",
    label: "Thumbnail",
    acceptedFormats: "JPG, PNG, GIF",
    maxSize: "2MB",
    files: [],
    formDataKey: "thumbnailImg",
    multiple: false,
    errorKey: "thumbnail",
  },
  {
    type: "file",
    mediaType: "pictures",
    label: "Pictures",
    acceptedFormats: "JPG, PNG, GIF. Up to 10 images, 2MB each (select up to 10 at once)",
    maxSize: "2MB each (max 10)",
    files: [],
    formDataKey: "pictures",
    multiple: true,
    errorKey: "pictures",
    required: true,
  },
  {
    type: "file",
    mediaType: "video",
    label: "Video",
    acceptedFormats: "MP4, MOV. Optional — up to 2 videos, 5MB each",
    maxSize: "5MB each (max 2)",
    files: [],
    formDataKey: "video",
    multiple: true,
    errorKey: "video",
    required: false,
  },
  {
    type: "file",
    mediaType: "qrScan",
    name: "qrScan",
    label: "QR Scan",
    acceptedFormats: "JPG, PNG, GIF",
    maxSize: "2MB",
    files: [],
    formDataKey: "qrScan",
    multiple: false,
    errorKey: "qrScan",
    required: false,
  },
  {
    type: "text",
    label: "DLD Number",
    placeholder: "DLD Number (issued by the Dubai Land Department)",
    name: "dldNumber",
    required: false,
  },
  {
    type: "textarea",
    label: "Tell us about your property",
    name: "description",
    placeholder: "Tell us about your Property (max. 300 characters)",
    maxLength: 300,
    required: true,
  },
  {
    type: "number",
    label: "Price",
    name: "price",
    placeholder: "Price",
    name: "price",
    required: true,
    unit: "AED",
  },
  {
    type: "textarea",
    label: "Additional Description",
    className: "!col-span-2 !row-span-2",
    placeholder: "Additional Description for your property",
    name: "additionalDescription",
    maxLength: 2000,
    required: true,
  },
  {
    type: "booking",
    name: "video3dwalkthrough",
    label: "Request 3D Walkthrough",
    placeholder: "3D Walkthrough Embedded Link",
    icon: "/icons/3dicon.png",
    required: false,
  },
  {
    type: "booking",
    label: "Request Technical Report",
    name: "technicalReport",
    placeholder: "Request Technical Report",
    icon: "/icons/card2.png",
    required: false,
  },

];

/** Shared base fields for off-plan listings on add-asset (no single price / evaluation booking). */
export const offPlanGlobalFormInputFields = [
  {
    type: "text",
    label: "Title your property",
    placeholder: "Title your property (max. 50 characters)",
    name: "title",
    maxLength: 50,
    required: true,
  },
  {
    type: "phoneNumber",
    label: "Phone Number",
    name: "phoneNumber",
    placeholder: "Enter your phone number",
    required: true,
  },
  {
    type: "file",
    mediaType: "thumbnail",
    name: "thumbnailImg",
    label: "Thumbnail",
    acceptedFormats: "JPG, PNG, GIF",
    maxSize: "2MB",
    files: [],
    formDataKey: "thumbnailImg",
    multiple: false,
    errorKey: "thumbnail",
    required: true,
  },
  {
    type: "file",
    mediaType: "pictures",
    name: "pictures",
    label: "Pictures",
    acceptedFormats: "JPG, PNG, GIF. Up to 10 images, 2MB each (select up to 10 at once)",
    maxSize: "2MB each (max 10)",
    files: [],
    formDataKey: "pictures",
    multiple: true,
    errorKey: "pictures",
    required: true,
  },
  {
    type: "file",
    mediaType: "video",
    name: "video",
    label: "Video",
    acceptedFormats: "MP4, MOV. Optional — up to 2 videos, 5MB each",
    maxSize: "5MB each (max 2)",
    files: [],
    formDataKey: "video",
    multiple: true,
    errorKey: "video",
    required: false,
  },
  {
    type: "file",
    mediaType: "qrScan",
    name: "qrScan",
    label: "QR Scan",
    acceptedFormats: "JPG, PNG, GIF",
    maxSize: "2MB",
    files: [],
    formDataKey: "qrScan",
    multiple: false,
    errorKey: "qrScan",
    required: false,
  },
  {
    type: "text",
    label: "DLD Number",
    placeholder: "DLD Number (issued by the Dubai Land Department)",
    name: "dldNumber",
    required: false,
  },
  {
    type: "textarea",
    label: "Tell us about your property",
    name: "description",
    placeholder: "Tell us about your property (max. 300 characters)",
    maxLength: 300,
    required: true,
  },
];

export const propertyFormFields = [
  {
    id: 1,
    type: "number",
    name: "sizeSQFT",
    placeholder: "Size in SQFT",
    required: true,
    unit: "SQFT",
  },
  {
    id: 2,
    type: "dropdown",
    name: "bedrooms",
    placeholder: "Bedrooms",
    options: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12+"],
    required: true,
  },
  {
    id: 3,
    type: "dropdown",
    name: "bathrooms",
    placeholder: "Bathrooms",
    options: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12+"],
    required: true,
  },
  {
    id: 4,
    type: "dropdown",
    name: "occupancyStatus",
    placeholder: "Occupancy Status",
    options: ["Vacant", "Occupied"],
    required: true,
  },
  {
    id: 5,
    type: "dropdown",
    name: "isFurnished",
    placeholder: "Is Furnished",
    options: ["Furnished", "Unfurnished"],
    required: false,
  },
  {
    id: 6,
    type: "text",
    name: "developer",
    placeholder: "Developer",
    required: false,
  },
];
export const leaseNumberofChequesOptions = ["1", "2", "3", "4", "5", "6"];

export const propertyLeaseFields = [
  {
    id: 4,
    type: "dropdown",
    name: "leaseNumberofCheques",
    placeholder: "Lease Number Of Cheques",
    options: leaseNumberofChequesOptions,
    required: true,
  },
];

export const Residential = [
  {
    id: 1,
    value: "Apartment",
  },
  {
    id: 2,
    value: "Villa",
  },
  {
    id: 3,
    value: "Townhouse",
  },
  {
    id: 4,
    value: "Multiple",
  },
  {
    id: 5,
    value: "Penthouse",
  },
  {
    id: 6,
    value: "Residential Building",
  },
  {
    id: 7,
    value: "Residential Floor",
  },
  {
    id: 8,
    value: "Villa Compound",
  },
];

export const Commercial = [
  {
    id: 1,
    value: "Office",
  },
  {
    id: 2,
    value: "Industrials",
  },
  {
    id: 3,
    value: "Retail",
  },
  {
    id: 4,
    value: "Staff Accommodation",
  },
  {
    id: 5,
    value: "Accommodation",
  },
  {
    id: 6,
    value: "Shop",
  },
  {
    id: 7,
    value: "Warehouse",
  },
  {
    id: 8,
    value: "Commercial Floor",
  },
  {
    id: 6,
    value: "Commercial Villa",
  },
  {
    id: 7,
    value: "Bulk Unit",
  },
  {
    id: 8,
    value: "Commercial Plot",
  },
  {
    id: 6,
    value: "Factory",
  },
  {
    id: 7,
    value: "Industrial Land",
  },
  {
    id: 8,
    value: "Mixed Use Land",
  },
  {
    id: 6,
    value: "Showroom",
  },
  {
    id: 7,
    value: "Commercial",
  },
  {
    id: 8,
    value: "Building",
  },
  {
    id: 8,
    value: "Other",
  },
];

export const propertyType = [
  {
    text: "Residential",
    state: "residential",
    mapData: Residential,
  },
  {
    text: "Commercial",
    state: "commercial",
    mapData: Commercial,
  },
  {
    text: "Multiple",
    state: "commercial",
  },
];
export const companiesOptions = ["Land Sterling Property Consultants LLC"];

export const facilities = [
  "Maids Room",
  "Private Garden",
  "Private Pool",
  "Concierge Service",
  "Built in Kitchen Appliances",
  "Balcony",
  "Study",
  "Shared Spa",
  "Private Gym",
  "Retail Outlets",
  "Private Jacuzzi",
  "Shared Pool",
  "Covered Parking",
  "Shared Gym",
  "Reception / Waiting Room",
  "Security",
  "Maid Service",
  "View of Landmark",
  "Laundry Room",
  "First Aid Medical Center",
  "Walk-in Closet",
  "View of Water",
  "Day Care Center",
  "Intercom",
  "Double Glazed Windows",
  "Pets Allowed",
  "Service Elevators",
  "Prayer Room",
  "Facilities for Disabled",
  "Built in Wardrobes",
  "Business Center",
  "Satellite / Cable TV",
  "Central heating",
  "Lobby in Building",
  "Recycling Facilities",
  "CCTV Security",
  "Kids Play Area",
  "Central A/C",
  "Barbeque Area",
  "Sport Courts",
  "Storage Areas",
  "Maintenance Staff",
  "Chiller A/C",
  "Cleaning Services",
];

export const propertyCheckBoxFields = [
  {
    id: 1,
    heading: "Listing",
    name: "listings",
    checkboxes: ["Private", "Public"],
  },
  {
    id: 2,
    heading: "Facilities",
    name: "facilities",
    checkboxes: facilities,
  },
];

// ________________CARS_________________

export const warrantyOptions = ["1 year", "2 years", "3 years", "No warranty"];

export const bodyConditionOptions = [
  "Flawless",
  "Excellent",
  "Average",
  "Poor",
];

export const evaluationPrices = ["2000", "3000", "4000"];

export const doorOptions = ["2 Door", "3 Door", "4 Door", "5+ Door"];

export const cylindersOptions = [
  "3",
  "4",
  "5",
  "6",
  "8",
  "10",
  "12",
  "Unknown",
];

export const engineCapacityOptions = [
  "0 - 499 cc",
  "500 - 999 cc",
  "1000 - 1499 cc",
  "1500 - 1999 cc",
  "2000 - 2499 cc",
  "2500 - 2999 cc",
  "3000 - 3499 cc",
  "3500 - 3999 cc",
  "4000+ cc",
  "Unknown",
];

export const horsepowerOptions = [
  "0 - 99 HP",
  "100 - 199 HP",
  "200 - 299 HP",
  "300 - 399 HP",
  "400 - 499 HP",
  "500 - 599 HP",
  "600 - 699 HP",
  "700 - 799 HP",
  "800 - 899 HP",
  "900+ HP",
  "Unknown",
];

export const seatingCapacityOptions = [
  "2 Seater",
  "4 Seater",
  "5 Seater",
  "6 Seater",
  "7 Seater",
  "8 Seater",
  "8+ Seater",
];

export const steeringSideOptions = ["Left Hand", "Right Hand"];

export const bodyTypeOptions = [
  "SUV",
  "Coupe",
  "Sedan",
  "Crossover",
  "Hard Top Convertible",
  "Pick Up Truck",
  "Hatchback",
  "Soft Top Convertible",
  "Sports Car",
  "Van",
  "Wagon",
  "Utility Truck",
  "Other",
];

export const transmissionTypeOptions = [
  "Transmission Type",
  "Manual Transmission",
  "Automatic Transmission",
];

export const fuelTypeOptions = [
  "Fuel Type",
  "Petrol",
  "Diesel",
  "Hybrid",
  "Electric",
];

export const carColors = [
  "Black",
  "Blue",
  "Brown",
  "Burgundy",
  "Gold",
  "Grey",
  "Orange",
  "Green",
  "Purple",
  "Red",
  "Silver",
  "Beige",
  "Tan",
  "Teal",
  "White",
  "Yellow",
  "Dark",
  "Light",
  "Pink",
  "DarkKhaki",
  "DarkGreen",
  "DarkBlue",
  "DarkCyan",
  "Aqua",
];

export const carTechnicalFeatures = [
  "Four Wheel Drive",
  "All Wheel Drive",
  "All Wheel Steering",
  "Cruise Control",
  "Anti-Lock Brakes/ABS",
  "Dual Exhaust",
  "Front Airbags",
  "Front Wheel Drive",
  "N2O System",
  "Rear Wheel Drive",
  "Power Steering",
  "Side Airbags",
  "Tiptronic Gears",
];

export const carExtras = [
  "Aux Audio In",
  "Body Kit",
  "Air Conditioning",
  "Bluetooth System",
  "Alarm/Anti-Theft System",
  "Am/Fm Radio",
  "Brush Guard",
  "Cassette Player",
  "Climate Control",
  "Cooled Seats",
  "CD Player",
  "Fog Lights",
  "DVD Player",
  "Heated Seats",
  "Navigation System",
  "Keyless Entry",
  "Keyless Start",
  "Leather Seats",
  "Moonroof",
  "Performace Tyres",
  "Off-Road Kit",
  "Off-Road Tyres",
  "Parking Sensors",
  "Power Locks",
  "Premium Sound System",
  "Power Mirrors",
  "Power Seats",
  "Power Sunroof",
  "Power Windows",
  "Premium Wheels/Rims",
  "Premium Lights",
  "Premium Paint",
  "Racing Seats",
  "Roof Rack",
  "Rear View Camera",
  "Roof Rack",
  "Spoiler",
  "Sunroof",
  "VHS Player",
  "Satellite Radios",
];

export const carFormFields = [
  {
    id: 1,
    type: "text",
    name: "size",
    placeholder: "Size",
    required: true,
  },
  {
    id: 2,
    type: "dropdown",
    name: "fuelType",
    placeholder: "Fuel Type",
    options: fuelTypeOptions,
    required: true,
  },
  {
    id: 3,
    type: "text",
    name: "kilometers",
    placeholder: "Kilometers",
    required: true,
  },
  {
    id: 4,
    type: "text",
    name: "year",
    placeholder: "Year",
    required: true,
  },
  {
    id: 5,
    type: "dropdown",
    name: "warranty",
    placeholder: "Warranty",
    options: warrantyOptions,
    required: true,
  },
  {
    id: 6,
    type: "text",
    name: "bodyCondition",
    placeholder: "Body Condition",
    options: bodyConditionOptions,
    required: true,
  },
  {
    id: 7,
    type: "text",
    name: "carType",
    placeholder: "Car Type",
    required: false,
  },
  {
    id: 8,
    type: "dropdown",
    name: "noOfCylinders",
    placeholder: "No. of Cylinders",
    options: cylindersOptions,
    required: true,
  },
  {
    id: 9,
    type: "text",
    name: "capacityWeight",
    placeholder: "Capacity/Weight",
    required: false,
  },
  {
    id: 10,
    type: "text",
    name: "mechanicalCondition",
    placeholder: "Mechanical Condition",
    required: false,
  },
  {
    id: 11,
    type: "dropdown",
    name: "seats",
    placeholder: "Seats",
    options: seatingCapacityOptions,
    required: true,
  },
  {
    id: 12,
    type: "dropdown",
    name: "bodyType",
    placeholder: "Body Type",
    options: bodyTypeOptions,
    required: true,
  },

  {
    id: 13,
    type: "dropdown",
    name: "doors",
    placeholder: "Doors",
    options: doorOptions,
    required: true,
  },
  {
    id: 14,
    type: "dropdown",
    name: "horsepower",
    placeholder: "Horsepower",
    options: horsepowerOptions,
    required: false,
  },

  {
    id: 15,
    type: "dropdown",
    name: "steeringSide",
    placeholder: "Steering Side",
    options: steeringSideOptions,
    required: true,
  },
  {
    id: 16,
    type: "dropdown",
    name: "transmissionType",
    placeholder: "Transmission Type",
    options: transmissionTypeOptions,
    required: true,
  },
  {
    id: 17,
    type: "text",
    name: "vinNumber",
    placeholder: "VIN Number",
    required: true,
  },
  {
    id: 18,
    type: "text",
    name: "engineCapacity",
    placeholder: "Engine Capacity",
    options: engineCapacityOptions,
    required: false,
  },
];

export const carBrands = [
  "Toyota",
  "Honda",
  "Ford",
  "Chevrolet",
  "Mercedes-Benz",
  "BMW",
  "Audi",
  "Sports Car",
  "Volkswagen",
  "Nissan",
  "Hyundai",
  "Kia",
  "Lexus",
  "Subaru",
  "Mazda",
  "Jaguar",
  "Land Rover",
  "Porsche",
  "Ferrari",
  "Lamborghini",
  "Tesla",
  "Volvo",
  "Mitsubishi",
  "Buick",
  "Cadillac",
  "Chrysler",
  "Dodge",
  "GMC",
  "Jeep",
  "Infiniti",
  "Acura",
  "Lincoln",
  "Alfa Romeo",
  "Bentley",
  "Maserati",
  "Rolls-Royce",
  "Aston Martin",
  "Mini",
  "Fiat",
  "Peugeot",
  "Citroën",
  "Renault",
  "Skoda",
  "Seat",
  "Suzuki",
  "Isuzu",
  "Saab",
  "Genesis",
  "McLaren",
  "Pagani",
  "Bugatti",
];

export const carCheckBoxFields = [
  {
    id: 1,
    heading: "Exterior Color",
    name: "exteriorColor",
    checkboxes: carColors,
  },
  {
    id: 2,
    heading: "Interior Color",
    name: "interiorColor",
    checkboxes: carColors,
  },
  {
    id: 3,
    heading: "Technical Features",
    name: "technicalFeatures",
    checkboxes: carTechnicalFeatures,
  },
  {
    id: 4,
    heading: "Extras",
    name: "extras",
    checkboxes: carExtras,
  },
];

//____________________Boat_______________________

export const usage = [
  "Still with the dealer",
  "Only used once since it was purchased new",
  "Used only a few times since it was purchased new",
  "Used only or twicw a month since purchased",
  "Used numerous times per week since purchased",
];
export const seller = ["Owner", "Dealer", "Dealership/Certified Pre-Owned"];
export const warrenty = ["Yes", "No", "Does not apply"];

export const boatExtrasList = [
  "Steel",
  "Aluminium",
  "Fibre-Reinforced",
  "Plastic",
  "Fibre-reinforced plastic",
  "Plywood",
  "Fibre",
  "Resin",
  "Ferrocement",
  "Gelcoat",
  "Kevlar",
  "Polyvinyl chloride",
  "Aux Audio In",
  "CD Player",
  "Premium Sound System",
  "Premium Lights",
  "DVD Player",
  "Power Seats",
  "Racing Seats",
  "Bluetooth System",
  "Private Pool",
  "Satellite / Cable TV",
  "Business Center",
  "Kids Play Area",
  "Prayer Room",
];

export const age = [
  "Brand New",
  "0-1 months",
  "1-6 months",
  "6-12 months",
  "1-2 years",
  "2-5 years",
  "5-10 years",
  "10+ years",
];

export const length = [
  "Under 10 ft.",
  "10-14 ft.",
  "15-19 ft.",
  "20-24 ft.",
  "25-29 ft.",
  "30-39 ft.",
  "40-49 ft.",
  "50-69 ft.",
  "70-100 ft.",
  "100+ ft.",
];

export const boatFormFields = [
  {
    id: 1,
    type: "dropdown",
    name: "length",
    placeholder: "Length",
    options: length,
    required: true,
  },
  {
    id: 2,
    type: "text",
    name: "brands",
    placeholder: "Brands",
    required: false,
  },
  {
    id: 3,
    type: "text",
    name: "locateBoat",
    placeholder: "Locate Your Boat",
    required: false,
  },
  {
    id: 4,
    type: "dropdown",
    name: "usage",
    placeholder: "Usage",
    options: usage,
    required: false,
  },
  {
    id: 5,
    type: "dropdown",
    name: "age",
    placeholder: "Age",
    options: age,
    required: true,
  },
  {
    id: 6,
    type: "text",
    name: "sportsOutdoorPrice",
    placeholder: "Sports & Outdoor Price",
    required: false,
  },
  {
    id: 7,
    type: "text",
    name: "seats",
    placeholder: "Seats",
    required: true,
  },
  {
    id: 8,
    type: "dropdown",
    name: "warrenty",
    placeholder: "Warrenty",
    options: warrenty,
    required: true,
  },
];
export const categories = {
  Motorboats: [
    "Cabin Cruiser Boat",
    "Cruiser Boat",
    "Fishing Boat",
    "Outboard Dayboat",
    "Ponton/House Boat",
    "Racing Boat",
    "Sleeper/Mini Yacht",
    "Wakeboarding/Ski Boat",
    "Yacht",
    "Other",
  ],
  "Row/Paddle Boats": ["Canoe/Row Boat", "Paddle Boat", "Other"],
  Sailboats: [
    "Catamaran",
    "Cruiser/Day Sailor",
    "DhowVoilier",
    "Dinghy",
    "Racer",
    "Sailing Yacht",
    "Other",
  ],
};
export const boatCategories = {
  Motorboats: [
    "Cabin Cruiser Boat",
    "Cruiser Boat",
    "Fishing Boat",
    "Outboard Dayboat",
    "Ponton/House Boat",
    "Racing Boat",
    "Sleeper/Mini Yacht",
    "Wakeboarding/Ski Boat",
    "Yacht",
    "Other",
  ],
  "Row/Paddle Boats": ["Canoe/Row Boat", "Paddle Boat", "Other"],
  Sailboats: [
    "Catamaran",
    "Cruiser/Day Sailor",
    "DhowVoilier",
    "Dinghy",
    "Racer",
    "Sailing Yacht",
    "Other",
  ],
};

export const boatCheckBoxFields = [
  {
    id: 1,
    heading: "Exterior Color",
    name: "exteriorColor",
    checkboxes: carColors,
  },
  {
    id: 2,
    heading: "Interior Color",
    name: "interiorColor",
    checkboxes: carColors,
  },
  {
    id: 3,
    heading: "Extras",
    name: "extras",
    checkboxes: boatExtrasList,
  },
];

// _________________Jewelery________________

export const conditionOptions = ["Flawless", "Excellent", "Average", "Poor"];

export const MenCategories = [
  "Belt Buckles",
  "Bracelets",
  "Chains & Necklaces",
  "Cufflinks",
  "Pins & Tie Clips",
  "Rings",
  "Studs",
  "Other",
];

export const WomenCategories = [
  "Body Jewelry",
  "Bracelets",
  "Earrings",
  "Ethnic & Artisan Jewelry",
  "Hair Jewelry",
  "Pins & Brooches",
  "Rings",
  "Other",
];

export const jeweleryCategories = [
  {
    name: "Men's Jewelry",
    sub: MenCategories,
  },
  {
    name: "Women's Jewelry",
    sub: WomenCategories,
  },
];

export const jeweleryAge = [
  "Brand New",
  "0-1 months",
  "1-6 months",
  "6-12 months",
  "1-2 years",
  "2-5 years",
  "5-10 years",
  "10+ years",
];

export const companies = ["Land Sterling Property Consultants LLC"];
export const materials = [
  "Amber",
  "Beads",
  "Bronze",
  "Ceramic",
  "Shell, Bone, Coral",
  "Crystal",
  "Diamond",
  "CZ",
  "Gemstone",
  "Leather",
  "Plastic",
  "Platinum",
  "Rhinestones",
  "Rubber",
  "Silver",
  "Steel",
  "Titanium",
  "White Gold",
  "Wood",
  "Yellow Gold",
  "Semi Precious/Birth Stones",
  "Other Material",
  "Other Metal",
];

export const jewelleryFormFields = [
  {
    id: 1,
    type: "text",
    name: "locateJewelry",
    placeholder: "Locate Your Jewellery",
    required: false,
  },
  {
    id: 2,
    type: "dropdown",
    name: "warrenty",
    placeholder: "Warrenty",
    options: warrenty,
    required: false,
  },
  {
    id: 3,
    type: "text",
    name: "lengthh",
    placeholder: "Length",
    required: false,
  },
  {
    id: 4,
    type: "text",
    name: "grams",
    placeholder: "Grams",
    required: true,
  },
  {
    id: 5,
    type: "dropdown",
    name: "usage",
    placeholder: "Usage",
    options: usage,
    required: true,
  },
  {
    id: 6,
    type: "dropdown",
    name: "age",
    placeholder: "Age",
    options: jeweleryAge,
    required: true,
  },
  {
    id: 7,
    type: "text",
    name: "jewelryStyles",
    placeholder: "Jewellery Styles",
    required: false,
  },
  {
    id: 8,
    type: "text",
    name: "jewelryMetal",
    placeholder: "Jewellery Metal",
    required: false,
  },
];
export const jewelleryCheckBoxFields = [
  {
    id: 1,
    heading: "Materials",
    name: "materials",
    checkboxes: materials,
  },
];
// ________________________________________________________________________________________________________________________________
export const data = [
  {
    Dubai: {
      Apartment: 2500,
      Villa: 3000,
      Townhouse: 2800,
      Multiple: 0,
      Penthouse: 0,
      "Residential Building": 10000,
      "Residential Floor": 0,
      "Villa Compound": 5000,
      Office: 2500,
      Industrials: 0,
      Retail: 2500,
      Staff: 0,
      Accommodation: 0,
      Shop: 2500,
      Warehouse: 0,
      "Commercial Floor": 0,
      "Commercial Villa": 0,
      "Bulk Unit": 0,
      "Commercial Plot": 7000,
      Factory: 0,
      "Industrial Land": 0,
      "Mixed Use Land": 0,
      Showroom: 0,
      Commercial: 0,
      Building: 15000,
      Other: 0,
    },
  },
  {
    "Abu Dhabi": {
      Apartment: 2500,
      Villa: 3000,
      Townhouse: 2800,
      Multiple: 0,
      Penthouse: 0,
      "Residential Building": 10000,
      "Residential Floor": 7000,
      "Villa Compound": 5000,
      Office: 2500,
      Industrials: 0,
      Retail: 2500,
      Staff: 0,
      Accommodation: 0,
      Shop: 2500,
      Warehouse: 0,
      "Commercial Floor": 0,
      "Commercial Villa": 0,
      "Bulk Unit": 0,
      "Commercial Plot": 7000,
      Factory: 0,
      "Industrial Land": 0,
      "Mixed Use Land": 0,
      Showroom: 0,
      Commercial: 0,
      Building: 15000,
      Other: 0,
    },
  },
  {
    "Sharjah & North Emirates": {
      Apartment: 2500,
      Villa: 3000,
      Townhouse: 2800,
      Multiple: 0,
      Penthouse: 0,
      "Residential Building": 10000,
      "Residential Floor": 7000,
      "Villa Compound": 5000,
      Office: 2500,
      Industrials: 0,
      Retail: 2500,
      Staff: 0,
      Accommodation: 0,
      Shop: 2500,
      Warehouse: 0,
      "Commercial Floor": 0,
      "Commercial Villa": 0,
      "Bulk Unit": 0,
      "Commercial Plot": 7000,
      Factory: 0,
      "Industrial Land": 0,
      "Mixed Use Land": 0,
      Showroom: 0,
      Commercial: 0,
      Building: 15000,
      Other: 0,
    },
  },
];

export const occupancyStatusOptions = ["Vacant", "Occupied"];

export const isFurnishedOptions = ["Furnished", "Unfurnished"];

export const bathroomsOptions = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12+",
];

export const bedroomsOptions = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12+",
];

export const deliveryQuarterOptions = ["Q1", "Q2", "Q3", "Q4"];

const currentYear = new Date().getFullYear();
export const deliveryYearOptions = Array.from({ length: 20 }, (_, i) =>
  String(currentYear + i),
);

export const sizeTypeOptions = ["SQFT", "SQM"];

export const layoutOptions = [
  "Studio",
  "1 BHK",
  "2 BHK",
  "2 BHK Duplex",
  "3 BHK",
  "3 BHK Duplex",
  "Penthouse",
  "Villa",
  "Townhouse",
];

export const numberOfFloorsOptions = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12+",
];

export const availableApartmentOptions = [
  "Studio",
  "1 BHK",
  "2 BHK",
  "2 BHK Duplex",
  "3 BHK Duplex",
  "Penthouse",
];

export const OFF_PLAN_LAYOUT_IMAGE_FORMATS_LABEL =
  "JPG, PNG, GIF. Maximum file size: 5MB";

export const apartmentLayoutUploads = [
  { key: "studioLayout", label: "Studio Unit Layout" },
  { key: "oneBhkLayout", label: "1 BHK Unit Layout" },
  { key: "twoBhkLayout", label: "2 BHK Unit Layout" },
  { key: "twoBhkDuplexLayout", label: "2 BHK Duplex Unit Layout" },
  { key: "threeBhkDuplexLayout", label: "3 BHK Duplex Unit Layout" },
  { key: "penthouseLayout", label: "Penthouse Unit Layout" },
];

export const OFF_PLAN_MEDIA_KEYS = [
  "unitLayout",
  "floorPlan",
];

export const createEmptyOffPlanMedia = () =>
  OFF_PLAN_MEDIA_KEYS.reduce((acc, key) => {
    acc[key] = null;
    return acc;
  }, {});

export const OFF_PLAN_PAYMENT_STEP_META = [
  { stepLabel: "1: First Step", paymentLabel: "Down Payment" },
  { stepLabel: "2: Second Step", paymentLabel: "Payment Share" },
  { stepLabel: "3: Third Step", paymentLabel: "Payment Share" },
  { stepLabel: "4: Fourth Step", paymentLabel: "Payment Share" },
  { stepLabel: "5: Fifth Step", paymentLabel: "Final Payment" },
];

export const MAX_OFF_PLAN_PAYMENT_STEPS = 10;
export const MIN_OFF_PLAN_PAYMENT_STEPS = 1;
export const DEFAULT_OFF_PLAN_PAYMENT_STEPS = 5;

const OFF_PLAN_STEP_ORDINALS = [
  "First",
  "Second",
  "Third",
  "Fourth",
  "Fifth",
  "Sixth",
  "Seventh",
  "Eighth",
  "Ninth",
  "Tenth",
];

export const getOffPlanPaymentLabel = (index, total) => {
  if (index === 0) return "Down Payment";
  if (total > 1 && index === total - 1) return "Final Payment";
  return "Payment Share";
};

export const reindexOffPlanPaymentPlan = (steps = []) =>
  steps.map((step, index) => ({
    ...step,
    step: index + 1,
    stepLabel: `${index + 1}: ${OFF_PLAN_STEP_ORDINALS[index] || `${index + 1}th`} Step`,
    paymentLabel: getOffPlanPaymentLabel(index, steps.length),
  }));

export const createDefaultOffPlanPaymentPlan = (
  count = DEFAULT_OFF_PLAN_PAYMENT_STEPS,
) =>
  reindexOffPlanPaymentPlan(
    Array.from(
      {
        length: Math.min(
          Math.max(count, MIN_OFF_PLAN_PAYMENT_STEPS),
          MAX_OFF_PLAN_PAYMENT_STEPS,
        ),
      },
      () => ({
        sharePercent: "",
        milestone: "",
      }),
    ),
  );

export const addOffPlanPaymentStep = (plan = []) => {
  if (plan.length >= MAX_OFF_PLAN_PAYMENT_STEPS) return plan;
  return reindexOffPlanPaymentPlan([
    ...plan,
    { sharePercent: "", milestone: "" },
  ]);
};

export const removeOffPlanPaymentStep = (plan = [], index) => {
  if (plan.length <= MIN_OFF_PLAN_PAYMENT_STEPS) return plan;
  return reindexOffPlanPaymentPlan(plan.filter((_, stepIndex) => stepIndex !== index));
};

export const asset = [
  { value: "Property For Sale", link: "property" },
  // { value: "Property For Lease", link: "property" },
  { value: "Property Off Plan For Sale", link: "property" },
  { value: "Car For Sale", link: "car" },
  { value: "Jewellery For Sale", link: "jewelry" },
  { value: "Boats For Sale", link: "boat" },
];

export const carForSale = [
  {
    brand: "Seat",
    models: [
      "Alhambra",
      "Altea",
      "Altea XL",
      "Arosa",
      "Cordoba",
      "Cordoba Vario",
      "Exeo",
      "Ibiza",
      "Ibiza ST",
      "Exeo ST",
      "Leon",
      "Leon ST",
      "Inca",
      "Mii",
      "Toledo",
    ],
  },
  {
    brand: "Renault",
    models: [
      "Captur",
      "Clio",
      "Clio Grandtour",
      "Espace",
      "Express",
      "Fluence",
      "Grand Espace",
      "Grand Modus",
      "Grand Scenic",
      "Kadjar",
      "Kangoo",
      "Kangoo Express",
      "Koleos",
      "Laguna",
      "Laguna Grandtour",
      "Latitude",
      "Mascott",
      "Mégane",
      "Mégane CC",
      "Mégane Combi",
      "Mégane Grandtour",
      "Mégane Coupé",
      "Mégane Scénic",
      "Scénic",
      "Talisman",
      "Talisman Grandtour",
      "Thalia",
      "Twingo",
      "Wind",
      "Zoé",
    ],
  },
  {
    brand: "Peugeot",
    models: [
      "1007",
      "107",
      "106",
      "108",
      "2008",
      "205",
      "205 Cabrio",
      "206",
      "206 CC",
      "206 SW",
      "207",
      "207 CC",
      "207 SW",
      "306",
      "307",
      "307 CC",
      "307 SW",
      "308",
      "308 CC",
      "308 SW",
      "309",
      "4007",
      "4008",
      "405",
      "406",
      "407",
      "407 SW",
      "5008",
      "508",
      "508 SW",
      "605",
      "806",
      "607",
      "807",
      "Bipper",
      "RCZ",
    ],
  },
  {
    brand: "Dacia",
    models: [
      "Dokker",
      "Duster",
      "Lodgy",
      "Logan",
      "Logan MCV",
      "Logan Van",
      "Sandero",
      "Solenza",
    ],
  },
  {
    brand: "Citroën",
    models: [
      "Berlingo",
      "C-Crosser",
      "C-Elissée",
      "C-Zero",
      "C1",
      "C2",
      "C3",
      "C3 Picasso",
      "C4",
      "C4 Aircross",
      "C4 Cactus",
      "C4 Coupé",
      "C4 Grand Picasso",
      "C4 Sedan",
      "C5",
      "C5 Break",
      "C5 Tourer",
      "C6",
      "C8",
      "DS3",
      "DS4",
      "DS5",
      "Evasion",
      "Jumper",
      "Jumpy",
      "Saxo",
      "Nemo",
      "Xantia",
      "Xsara",
    ],
  },
  {
    brand: "Opel",
    models: [
      "Agila",
      "Ampera",
      "Antara",
      "Astra",
      "Astra cabrio",
      "Astra caravan",
      "Astra coupé",
      "Calibra",
      "Campo",
      "Cascada",
      "Corsa",
      "Frontera",
      "Insignia",
      "Insignia kombi",
      "Kadett",
      "Meriva",
      "Mokka",
      "Movano",
      "Omega",
      "Signum",
      "Vectra",
      "Vectra Caravan",
      "Vivaro",
      "Vivaro Kombi",
      "Zafira",
    ],
  },
  {
    brand: "Alfa Romeo",
    models: [
      "145",
      "146",
      "147",
      "155",
      "156",
      "156 Sportwagon",
      "159",
      "159 Sportwagon",
      "164",
      "166",
      "4C",
      "Brera",
      "GTV",
      "MiTo",
      "Crosswagon",
      "Spider",
      "GT",
      "Giulietta",
      "Giulia",
    ],
  },
  {
    brand: "Škoda",
    models: [
      "Favorit",
      "Felicia",
      "Citigo",
      "Fabia",
      "Fabia Combi",
      "Fabia Sedan",
      "Felicia Combi",
      "Octavia",
      "Octavia Combi",
      "Roomster",
      "Yeti",
      "Rapid",
      "Rapid Spaceback",
      "Superb",
      "Superb Combi",
    ],
  },
  {
    brand: "Chevrolet",
    models: [
      "Alero",
      "Aveo",
      "Camaro",
      "Captiva",
      "Corvette",
      "Cruze",
      "Cruze SW",
      "Epica",
      "Equinox",
      "Evanda",
      "HHR",
      "Kalos",
      "Lacetti",
      "Lacetti SW",
      "Lumina",
      "Malibu",
      "Matiz",
      "Monte Carlo",
      "Nubira",
      "Orlando",
      "Spark",
      "Suburban",
      "Tacuma",
      "Tahoe",
      "Trax",
    ],
  },
  {
    brand: "Porsche",
    models: [
      "911 Carrera",
      "911 Carrera Cabrio",
      "911 Targa",
      "911 Turbo",
      "924",
      "944",
      "997",
      "Boxster",
      "Cayenne",
      "Cayman",
      "Macan",
      "Panamera",
    ],
  },
  {
    brand: "Honda",
    models: [
      "Accord",
      "Accord Coupé",
      "Accord Tourer",
      "City",
      "Civic",
      "Civic Aerodeck",
      "Civic Coupé",
      "Civic Tourer",
      "Civic Type R",
      "CR-V",
      "CR-X",
      "CR-Z",
      "FR-V",
      "HR-V",
      "Insight",
      "Integra",
      "Jazz",
      "Legend",
      "Prelude",
    ],
  },
  {
    brand: "Subaru",
    models: [
      "BRZ",
      "Forester",
      "Impreza",
      "Impreza Wagon",
      "Justy",
      "Legacy",
      "Legacy Wagon",
      "Legacy Outback",
      "Levorg",
      "Outback",
      "SVX",
      "Tribeca",
      "Tribeca B9",
      "XV",
    ],
  },
  {
    brand: "Mazda",
    models: [
      "121",
      "2",
      "3",
      "323",
      "323 Combi",
      "323 Coupé",
      "323 F",
      "5",
      "6",
      "6 Combi",
      "626",
      "626 Combi",
      "B-Fighter",
      "B2500",
      "BT",
      "CX-3",
      "CX-5",
      "CX-7",
      "CX-9",
      "Demio",
      "MPV",
      "MX-3",
      "MX-5",
      "MX-6",
      "Premacy",
      "RX-7",
      "RX-8",
      "Xedox 6",
    ],
  },
  {
    brand: "Mitsubishi",
    models: [
      "3000 GT",
      "ASX",
      "Carisma",
      "Colt",
      "Colt CC",
      "Eclipse",
      "Fuso canter",
      "Galant",
      "Galant Combi",
      "Grandis",
      "L200",
      "L200 Pick up",
      "L200 Pick up Allrad",
      "L300",
      "Lancer",
      "Lancer Combi",
      "Lancer Evo",
      "Lancer Sportback",
      "Outlander",
      "Pajero",
      "Pajeto Pinin",
      "Pajero Pinin Wagon",
      "Pajero Sport",
      "Pajero Wagon",
      "Space Star",
    ],
  },
  {
    brand: "Lexus",
    models: [
      "CT",
      "GS",
      "GS 300",
      "GX",
      "IS",
      "IS 200",
      "IS 250 C",
      "IS-F",
      "LS",
      "LX",
      "NX",
      "RC F",
      "RX",
      "RX 300",
      "RX 400h",
      "RX 450h",
      "SC 430",
    ],
  },
  {
    brand: "Toyota",
    models: [
      "4-Runner",
      "Auris",
      "Avensis",
      "Avensis Combi",
      "Avensis Van Verso",
      "Aygo",
      "Camry",
      "Carina",
      "Celica",
      "Corolla",
      "Corolla Combi",
      "Corolla sedan",
      "Corolla Verso",
      "FJ Cruiser",
      "GT86",
      "Hiace",
      "Hiace Van",
      "Highlander",
      "Hilux",
      "Land Cruiser",
      "MR2",
      "Paseo",
      "Picnic",
      "Prius",
      "RAV4",
      "Sequoia",
      "Starlet",
      "Supra",
      "Tundra",
      "Urban Cruiser",
      "Verso",
      "Yaris",
      "Yaris Verso",
    ],
  },
  {
    brand: "BMW",
    models: [
      "i3",
      "i8",
      "M3",
      "M4",
      "M5",
      "M6",
      "Rad 1",
      "Rad 1 Cabrio",
      "Rad 1 Coupé",
      "Rad 2",
      "Rad 2 Active Tourer",
      "Rad 2 Coupé",
      "Rad 2 Gran Tourer",
      "Rad 3",
      "Rad 3 Cabrio",
      "Rad 3 Compact",
      "Rad 3 Coupé",
      "Rad 3 GT",
      "Rad 3 Touring",
      "Rad 4",
      "Rad 4 Cabrio",
      "Rad 4 Gran Coupé",
      "Rad 5",
      "Rad 5 GT",
      "Rad 5 Touring",
      "Rad 6",
      "Rad 6 Cabrio",
      "Rad 6 Coupé",
      "Rad 6 Gran Coupé",
      "Rad 7",
      "Rad 8 Coupé",
      "X1",
      "X3",
      "X4",
      "X5",
      "X6",
      "Z3",
      "Z3 Coupé",
      "Z3 Roadster",
      "Z4",
      "Z4 Roadster",
    ],
  },
  {
    brand: "Volkswagen",
    models: [
      "Amarok",
      "Beetle",
      "Bora",
      "Bora Variant",
      "Caddy",
      "Caddy Van",
      "Life",
      "California",
      "Caravelle",
      "CC",
      "Crafter",
      "Crafter Van",
      "Crafter Kombi",
      "CrossTouran",
      "Eos",
      "Fox",
      "Golf",
      "Golf Cabrio",
      "Golf Plus",
      "Golf Sportvan",
      "Golf Variant",
      "Jetta",
      "LT",
      "Lupo",
      "Multivan",
      "New Beetle",
      "New Beetle Cabrio",
      "Passat",
      "Passat Alltrack",
      "Passat CC",
      "Passat Variant",
      "Passat Variant Van",
      "Phaeton",
      "Polo",
      "Polo Van",
      "Polo Variant",
      "Scirocco",
      "Sharan",
      "T4",
      "T4 Caravelle",
      "T4 Multivan",
      "T5",
      "T5 Caravelle",
      "T5 Multivan",
      "T5 Transporter Shuttle",
      "Tiguan",
      "Touareg",
      "Touran",
    ],
  },
  {
    brand: "Suzuki",
    models: [
      "Alto",
      "Baleno",
      "Baleno kombi",
      "Grand Vitara",
      "Grand Vitara XL-7",
      "Ignis",
      "Jimny",
      "Kizashi",
      "Liana",
      "Samurai",
      "Splash",
      "Swift",
      "SX4",
      "SX4 Sedan",
      "Vitara",
      "Wagon R+",
    ],
  },
  {
    brand: "Mercedes-Benz",
    models: [
      "100 D",
      "115",
      "124",
      "126",
      "190",
      "190 D",
      "190 E",
      "200 - 300",
      "200 D",
      "200 E",
      "210 Van",
      "210 kombi",
      "310 Van",
      "310 kombi",
      "230 - 300 CE Coupé",
      "260 - 560 SE",
      "260 - 560 SEL",
      "500 - 600 SEC Coupé",
      "Trieda A",
      "A",
      "A L",
      "AMG GT",
      "Trieda B",
      "Trieda C",
      "C",
      "C Sportcoupé",
      "C T",
      "Citan",
      "CL",
      "CL",
      "CLA",
      "CLC",
      "CLK Cabrio",
      "CLK Coupé",
      "CLS",
      "Trieda E",
      "E",
      "E Cabrio",
      "E Coupé",
      "E T",
      "Trieda G",
      "G Cabrio",
      "GL",
      "GLA",
      "GLC",
      "GLE",
      "GLK",
      "Trieda M",
      "MB 100",
      "Trieda R",
      "Trieda S",
      "S",
      "S Coupé",
      "SL",
      "SLC",
      "SLK",
      "SLR",
      "Sprinter",
    ],
  },
  {
    brand: "Saab",
    models: [
      "9-3",
      "9-3 Cabriolet",
      "9-3 Coupé",
      "9-3 SportCombi",
      "9-5",
      "9-5 SportCombi",
      "900",
      "900 C",
      "900 C Turbo",
      "9000",
    ],
  },
  {
    brand: "Audi",
    models: [
      "100",
      "100 Avant",
      "80",
      "80 Avant",
      "80 Cabrio",
      "90",
      "A1",
      "A2",
      "A3",
      "A3 Cabriolet",
      "A3 Limuzina",
      "A3 Sportback",
      "A4",
      "A4 Allroad",
      "A4 Avant",
      "A4 Cabriolet",
      "A5",
      "A5 Cabriolet",
      "A5 Sportback",
      "A6",
      "A6 Allroad",
      "A6 Avant",
      "A7",
      "A8",
      "A8 Long",
      "Q3",
      "Q5",
      "Q7",
      "R8",
      "RS4 Cabriolet",
      "RS4/RS4 Avant",
      "RS5",
      "RS6 Avant",
      "RS7",
      "S3/S3 Sportback",
      "S4 Cabriolet",
      "S4/S4 Avant",
      "S5/S5 Cabriolet",
      "S6/RS6",
      "S7",
      "S8",
      "SQ5",
      "TT Coupé",
      "TT Roadster",
      "TTS",
    ],
  },
  {
    brand: "Kia",
    models: [
      "Avella",
      "Besta",
      "Carens",
      "Carnival",
      "Cee`d",
      "Cee`d SW",
      "Cerato",
      "K 2500",
      "Magentis",
      "Opirus",
      "Optima",
      "Picanto",
      "Pregio",
      "Pride",
      "Pro Cee`d",
      "Rio",
      "Rio Combi",
      "Rio sedan",
      "Sephia",
      "Shuma",
      "Sorento",
      "Soul",
      "Sportage",
      "Venga",
    ],
  },
  {
    brand: "Land Rover",
    models: [
      "109",
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
    ],
  },
  {
    brand: "Dodge",
    models: [
      "Avenger",
      "Caliber",
      "Challenger",
      "Charger",
      "Grand Caravan",
      "Journey",
      "Magnum",
      "Nitro",
      "RAM",
      "Stealth",
      "Viper",
    ],
  },
  {
    brand: "Chrysler",
    models: [
      "300 C",
      "300 C Touring",
      "300 M",
      "Crossfire",
      "Grand Voyager",
      "LHS",
      "Neon",
      "Pacifica",
      "Plymouth",
      "PT Cruiser",
      "Sebring",
      "Sebring Convertible",
      "Stratus",
      "Stratus Cabrio",
      "Town & Country",
      "Voyager",
    ],
  },
  {
    brand: "Ford",
    models: [
      "Aerostar",
      "B-Max",
      "C-Max",
      "Cortina",
      "Cougar",
      "Edge",
      "Escort",
      "Escort Cabrio",
      "Escort kombi",
      "Explorer",
      "F-150",
      "F-250",
      "Fiesta",
      "Focus",
      "Focus C-Max",
      "Focus CC",
      "Focus kombi",
      "Fusion",
      "Galaxy",
      "Grand C-Max",
      "Ka",
      "Kuga",
      "Maverick",
      "Mondeo",
      "Mondeo Combi",
      "Mustang",
      "Orion",
      "Puma",
      "Ranger",
      "S-Max",
      "Sierra",
      "Street Ka",
      "Tourneo Connect",
      "Tourneo Custom",
      "Transit",
      "Transit",
      "Transit Bus",
      "Transit Connect LWB",
      "Transit Courier",
      "Transit Custom",
      "Transit kombi",
      "Transit Tourneo",
      "Transit Valnik",
      "Transit Van",
      "Transit Van 350",
      "Windstar",
    ],
  },
  { brand: "Hummer", models: ["H2", "H3"] },
  {
    brand: "Hyundai",
    models: [
      "Accent",
      "Atos",
      "Atos Prime",
      "Coupé",
      "Elantra",
      "Galloper",
      "Genesis",
      "Getz",
      "Grandeur",
      "H 350",
      "H1",
      "H1 Bus",
      "H1 Van",
      "H200",
      "i10",
      "i20",
      "i30",
      "i30 CW",
      "i40",
      "i40 CW",
      "ix20",
      "ix35",
      "ix55",
      "Lantra",
      "Matrix",
      "Santa Fe",
      "Sonata",
      "Terracan",
      "Trajet",
      "Tucson",
      "Veloster",
    ],
  },
  { brand: "Infiniti", models: ["EX", "FX", "G", "G Coupé", "M", "Q", "QX"] },
  {
    brand: "Jaguar",
    models: [
      "Daimler",
      "F-Pace",
      "F-Type",
      "S-Type",
      "Sovereign",
      "X-Type",
      "X-type Estate",
      "XE",
      "XF",
      "XJ",
      "XJ12",
      "XJ6",
      "XJ8",
      "XJ8",
      "XJR",
      "XK",
      "XK8 Convertible",
      "XKR",
      "XKR Convertible",
    ],
  },
  {
    brand: "Jeep",
    models: [
      "Cherokee",
      "Commander",
      "Compass",
      "Grand Cherokee",
      "Patriot",
      "Renegade",
      "Wrangler",
    ],
  },
  {
    brand: "Nissan",
    models: [
      "100 NX",
      "200 SX",
      "350 Z",
      "350 Z Roadster",
      "370 Z",
      "Almera",
      "Almera Tino",
      "Cabstar E - T",
      "Cabstar TL2 Valnik",
      "e-NV200",
      "GT-R",
      "Insterstar",
      "Juke",
      "King Cab",
      "Leaf",
      "Maxima",
      "Maxima QX",
      "Micra",
      "Murano",
      "Navara",
      "Note",
      "NP300 Pickup",
      "NV200",
      "NV400",
      "Pathfinder",
      "Patrol",
      "Patrol GR",
      "Pickup",
      "Pixo",
      "Primastar",
      "Primastar Combi",
      "Primera",
      "Primera Combi",
      "Pulsar",
      "Qashqai",
      "Serena",
      "Sunny",
      "Terrano",
      "Tiida",
      "Trade",
      "Vanette Cargo",
      "X-Trail",
    ],
  },
  {
    brand: "Volvo",
    models: [
      "240",
      "340",
      "360",
      "460",
      "850",
      "850 kombi",
      "C30",
      "C70",
      "C70 Cabrio",
      "C70 Coupé",
      "S40",
      "S60",
      "S70",
      "S80",
      "S90",
      "V40",
      "V50",
      "V60",
      "V70",
      "V90",
      "XC60",
      "XC70",
      "XC90",
    ],
  },
  {
    brand: "Daewoo",
    models: [
      "Espero",
      "Kalos",
      "Lacetti",
      "Lanos",
      "Leganza",
      "Lublin",
      "Matiz",
      "Nexia",
      "Nubira",
      "Nubira kombi",
      "Racer",
      "Tacuma",
      "Tico",
    ],
  },
  {
    brand: "Fiat",
    models: [
      "1100",
      "126",
      "500",
      "500L",
      "500X",
      "850",
      "Barchetta",
      "Brava",
      "Cinquecento",
      "Coupé",
      "Croma",
      "Doblo",
      "Doblo Cargo",
      "Doblo Cargo Combi",
      "Ducato",
      "Ducato Van",
      "Ducato Kombi",
      "Ducato Podvozok",
      "Florino",
      "Florino Combi",
      "Freemont",
      "Grande Punto",
      "Idea",
      "Linea",
      "Marea",
      "Marea Weekend",
      "Multipla",
      "Palio Weekend",
      "Panda",
      "Panda Van",
      "Punto",
      "Punto Cabriolet",
      "Punto Evo",
      "Punto Van",
      "Qubo",
      "Scudo",
      "Scudo Van",
      "Scudo Kombi",
      "Sedici",
      "Seicento",
      "Stilo",
      "Stilo Multiwagon",
      "Strada",
      "Talento",
      "Tipo",
      "Ulysse",
      "Uno",
      "X1/9",
    ],
  },
  {
    brand: "MINI",
    models: [
      "Cooper",
      "Cooper Cabrio",
      "Cooper Clubman",
      "Cooper D",
      "Cooper D Clubman",
      "Cooper S",
      "Cooper S Cabrio",
      "Cooper S Clubman",
      "Countryman",
      "Mini One",
      "One D",
    ],
  },
  {
    brand: "Rover",
    models: ["200", "214", "218", "25", "400", "414", "416", "620", "75"],
  },
  {
    brand: "Smart",
    models: [
      "Cabrio",
      "City-Coupé",
      "Compact Pulse",
      "Forfour",
      "Fortwo cabrio",
      "Fortwo coupé",
      "Roadster",
    ],
  },
];
